spring.application.name=SistemaRestaurante
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/sazon_fuego
spring.datasource.username=root
spring.datasource.password=1212
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true